# Generated by Django 5.2.2 on 2025-06-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
    ]
