# Generated by Django 5.2.2 on 2025-06-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_core', '0002_note_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Download Count'),
        ),
    ]
